apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deploy
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: mostafaabdelkhalek8/go-app
          ports:
            - containerPort: 8050  # Corrected syntax here
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-db-svc:27017"
            - name: SERVER_PORT
              value: "8050"
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017