pipeline {
    agent { label 'slave' }

    stages {
        stage('deploy app') {
            steps {
                script {
                    sh """
                    kubectl apply -f deployment.yml
                    kubectl apply -f svc.yml
                    """
                }
            }
        }
    }
}
